[MIG] Ubuntu 22.04 changes
akretion/pywebdriver pull request #110
Opened 2022-09-05 13:32 UTC by quentinDupont

2022-09-05 14:54 UTC, PierrickBrun commented
quick code review: looks good

I hope it will not break any backward compatibility but I'm not sure about it.

If 18.04 breaksI think this is not a problem but if 18 and 20 breaks we may have to create a "focal" branch to maintain it

2022-09-05 19:34 UTC, rvalyi commented
that being said, a rebase will probably be required as the pre-commit cleanup will probably conflict with https://github.com/akretion/pywebdriver/pull/109 (not sure why the merge is still running BTW).

2022-10-03 15:36 UTC, rvalyi approved these changes
LGTM (disclaimer I'm not an expert in Debian packages).

2022-10-10 15:12 UTC, quentinDupont commented
build.sh for ubuntu 22 has done the job well. Stil need to test it with real printer etc. Coming soon

2022-11-18 16:45 UTC, quentinDupont commented
Changes for Ubuntu 22.04 version :heavy_check_mark: 

Build.sh functional :heavy_check_mark: 

Improve also install.sh 
- indempotent
- option for https or not
- upgrade mkcert version to 1.4.4 to make it work on Firefox again


Tested on two new Ubuntu 22.04 computers, for Epson TMT20-III, customer display and one payment device

2022-11-19 14:13 UTC, rvalyi commented on .pre-commit-config.yaml
> +  - repo: https://github.com/PyCQA/flake8
le commit de connaisseur!  ;-)

2022-11-19 14:16 UTC, rvalyi requested changes
LGTM but without test nor extreme care in the review on my side.

2022-11-19 14:16 UTC, rvalyi approved these changes
LGTM but without test nor extreme care in the review on my side.

2022-11-21 16:18 UTC, quentinDupont commented on .pre-commit-config.yaml
> +  - repo: https://github.com/PyCQA/flake8
je dois tout à @legalsylvain qui a fait ce commit dans nos repos ;) j'avais pas compris sur le moment, j'ai compris quand ça a pété ici !

2023-02-14 10:59 UTC, quentinDupont commented
How can we make it go forward ? :) 

At the moment, to be tested, to install it, you need to :
- compile or download new .deb here https://nuage.grap.coop/s/YRetJsiiPiZpjn9 (waiting github actions when it will be merged)
- download install.sh https://github.com/akretion/pywebdriver/blob/554cca7110e0d3634248d9a26682382f3b9d54b6/debian/install.sh
- make it executable
- change lines to install .deb that we just downloaded
- ./install.sh
- change lines in /etc/pywebdriver/config.ini to add
sslcert=/etc/pywebdriver/cert/localhost+1.pem
sslkey=/etc/pywebdriver/cert/localhost+1-key.pem
(it will be automatic but config file is changed is this PR)
- restart pywebdriver ` sudo service pywebdriver restart`
- Check in https://localhost:8069 to accept certificate
- it should be all good

2023-02-14 11:04 UTC, merged

2023-02-14 19:09 UTC, quentinDupont commented
Thank youu @PierrickBrun !!